// <auto-generated />
using InClass6s.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InClass6s.Migrations
{
    [DbContext(typeof(SmithContext))]
    [Migration("20250227210645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InClass6s.Models.Activitys", b =>
                {
                    b.Property<int>("activityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activityID"));

                    b.Property<string>("activityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activityLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fireteamSize")
                        .HasColumnType("int");

                    b.Property<bool>("isMatchMade")
                        .HasColumnType("bit");

                    b.HasKey("activityID");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            activityID = 1,
                            activityDescription = "A timeless Vex raid that challenges Guardians with puzzles and powerful foes.",
                            activityLocation = "Venus",
                            activityName = "Vault of Glass",
                            activityType = "Raid",
                            difficulty = "Master",
                            fireteamSize = 6,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 2,
                            activityDescription = "A raid deep within the Dreaming City to defeat Riven, the final Ahamkara.",
                            activityLocation = "Dreaming City",
                            activityName = "Last Wish",
                            activityType = "Raid",
                            difficulty = "Master",
                            fireteamSize = 6,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 3,
                            activityDescription = "A raid set on Europa, uncovering the secrets of Clovis Bray and the Exo origin.",
                            activityLocation = "Europa",
                            activityName = "Deep Stone Crypt",
                            activityType = "Raid",
                            difficulty = "Master",
                            fireteamSize = 6,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 4,
                            activityDescription = "A raid against Oryx, the Taken King, deep within the Dreadnaught.",
                            activityLocation = "Dreadnaught",
                            activityName = "King’s Fall",
                            activityType = "Raid",
                            difficulty = "Master",
                            fireteamSize = 6,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 5,
                            activityDescription = "A raid against Nezarec aboard the Witness’s Pyramid ship.",
                            activityLocation = "Pyramid Ship",
                            activityName = "Root of Nightmares",
                            activityType = "Raid",
                            difficulty = "Master",
                            fireteamSize = 6,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 6,
                            activityDescription = "A dungeon inside Calus’ mind to uncover secrets of the Leviathan.",
                            activityLocation = "Leviathan",
                            activityName = "Duality",
                            activityType = "Dungeon",
                            difficulty = "Master",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 7,
                            activityDescription = "A dungeon to prevent a Vex incursion in a Braytech facility.",
                            activityLocation = "Mars",
                            activityName = "Spire of the Watcher",
                            activityType = "Dungeon",
                            difficulty = "Master",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 8,
                            activityDescription = "A dungeon set beneath the oceans of Titan against the Lucent Hive.",
                            activityLocation = "Titan",
                            activityName = "Ghosts of the Deep",
                            activityType = "Dungeon",
                            difficulty = "Master",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 9,
                            activityDescription = "A high-stakes version of a Strike with increasing difficulty tiers.",
                            activityLocation = "Varies",
                            activityName = "Nightfall: The Ordeal (Normal)",
                            activityType = "Strike",
                            difficulty = "Normal",
                            fireteamSize = 3,
                            isMatchMade = true
                        },
                        new
                        {
                            activityID = 10,
                            activityDescription = "A high-stakes version of a Strike with increasing difficulty tiers.",
                            activityLocation = "Varies",
                            activityName = "Nightfall: The Ordeal (Legend)",
                            activityType = "Strike",
                            difficulty = "Legend",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 11,
                            activityDescription = "A high-stakes version of a Strike with increasing difficulty tiers.",
                            activityLocation = "Varies",
                            activityName = "Nightfall: The Ordeal (Master)",
                            activityType = "Strike",
                            difficulty = "Master",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 12,
                            activityDescription = "A brutal test of skill with Champions and deadly modifiers.",
                            activityLocation = "Varies",
                            activityName = "Nightfall: The Ordeal (Grandmaster)",
                            activityType = "Strike",
                            difficulty = "Grandmaster",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 13,
                            activityDescription = "A pinnacle 3v3 PvP activity that rewards flawless victories.",
                            activityLocation = "The Crucible",
                            activityName = "Trials of Osiris",
                            activityType = "PvP",
                            difficulty = "High Difficulty",
                            fireteamSize = 3,
                            isMatchMade = false
                        },
                        new
                        {
                            activityID = 14,
                            activityDescription = "A week-long PvP event where power level matters.",
                            activityLocation = "The Crucible",
                            activityName = "Iron Banner",
                            activityType = "PvP",
                            difficulty = "Normal",
                            fireteamSize = 6,
                            isMatchMade = true
                        },
                        new
                        {
                            activityID = 15,
                            activityDescription = "A competitive PvP mode where lives are limited.",
                            activityLocation = "The Crucible",
                            activityName = "Survival",
                            activityType = "PvP",
                            difficulty = "Legend",
                            fireteamSize = 3,
                            isMatchMade = true
                        },
                        new
                        {
                            activityID = 16,
                            activityDescription = "A hybrid PvPvE mode where two teams compete to defeat enemies and summon a Primeval.",
                            activityLocation = "The Drifter's Arena",
                            activityName = "Gambit",
                            activityType = "PvPvE",
                            difficulty = "Normal",
                            fireteamSize = 4,
                            isMatchMade = true
                        },
                        new
                        {
                            activityID = 17,
                            activityDescription = "A game show-style activity hosted by Xûr with rotating challenges.",
                            activityLocation = "Eternity",
                            activityName = "Dares of Eternity",
                            activityType = "PvE",
                            difficulty = "Legend",
                            fireteamSize = 6,
                            isMatchMade = true
                        },
                        new
                        {
                            activityID = 18,
                            activityDescription = "A more difficult version of the campaign offering better rewards.",
                            activityLocation = "Varies",
                            activityName = "Legendary Campaign",
                            activityType = "PvE",
                            difficulty = "Legend",
                            fireteamSize = 1,
                            isMatchMade = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
